[package]
name = "techshare-mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
base64 = "0.22.1"
reqwest = {version="0.13", features=["query","json"]}
rust-mcp-sdk = {version="0.8"}
serde = "1.0"
serde_json = "1.0"
tokio = "1.49"
